interface ThemeInterface {
    appContainer: { [property: string]: string | number },
    homeScreen: { [property: string]: string | number },
    homeHeader: { [property: string]: string | number },
    homeHeaderIcon: { [property: string]: string | number },
    homeHeaderText: { [property: string]: string | number },
    bottomView: { [property: string]: string | number },
    newListButton: { [property: string]: string | number },
    newListButtonText: { [property: string]: string | number },
    shadow: { [property: string]: string | number },
    shoppingListScreen: { [property: string]: string | number },
    header: { [property: string]: string | number },
    headerIcon: { [property: string]: string | number },
    headerText: { [property: string]: string | number },
    shoppingList: { [property: string]: string | number },
    item: { [property: string]: string | number },
    itemActive: { [property: string]: string | number },
    itemView: { [property: string]: string | number },
    itemInnerLeftView: { [property: string]: string | number },
    itemInnerRightView: { [property: string]: string | number },
    itemText: { [property: string]: string | number },
    itemIcon: { [property: string]: string | number },
}

export default ThemeInterface;
